config/routes.rb
Rails.application.routes.draw do
  get 'questions' => 'questions#index'
  get 'questions/:id' => 'questions#show', as: :question

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
        @questions = Question.all
    end

    def show
        @question = Question.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
	def format_body(question)
		if question.body.present?
		    # note you can call a helper from a helper
		    truncate(question.body, length: 20, separator: ' ')
		else
		    '<i>n/a</i>'
		end
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Questionable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<h3>Questions</h3>


<h3><%= pluralize(@questions.count, 'Question') %></h3>
<table border="1" >
  <thead>
  <tr>
     <th>Title</th>
     <th>Body</th>
     <th>Posted On</th>
  </tr>
  </thead>
  <tbody>
  <% @questions.each do |question| %>
  <tr>
     <td><%= link_to(question.title,  question_path(question.id)) %></td>
     <td><%= format_body(question) %></td>
       <td><%= question.created_at.to_s(:short) %></td>
  </tr>
  <% end %>  
  </tbody>
</table>

app/views/questions/show.html.erb
<h3><%= @question.title %></h3>

<p><%= @question.body %></p>

<%= link_to "Back to Questions", questions_path %>